### PR TITLE
Picviewer CE+ pt-BR translation

### PR DESCRIPTION
**Pull request by thiagojramos**
Completely redid the pt-BR translation from scratch, starting with the en-us strings to ensure greater clarity and consistency.

### CODE REVIEW

**Comment by hoothin** [comment]
Thank you for the translation, but perhaps you could create a separate language item using match: ["pt-BR"] & deleting the existing "pt-BR" to distinguish Portuguese from Brazilian Portuguese.

**Comment by thiagojramos** [comment]
Alright. I had replaced it because, in my view, the previous translation was in Brazilian Portuguese, not European Portuguese. In European Portuguese, they use "Ficheiro" instead of "Arquivo" and "A carregar..." instead of "Carregando..."

I'll put it in draft mode and handle it later.

**Comment by thiagojramos** [comment]
This is how you wanted it, right?

**Comment by hoothin** [comment]
Yes, thank you for your contribution!

**Pull request merged**
