### PR TITLE
Update and rename pagetual.user.js to pagetual_arabic_user.js

### PR DESCRIPTION
**Pull request by vfggf95565**
Adding Arabic translation for Arabic users. (There are a lot of users in Arabic)

### CODE REVIEW

**Comment by hoothin** [comment]
Thank you for translation but why rename?

**Comment by vfggf95565** [comment]
I'm sorry for changing the name, but I didn't want to change the name, I just wanted to attract your attention by changing the name. I am a native Arabic speaker and wanted to add Arabic translation, specifically about the meme, because we don't have many memes in the Arab market. Most games are not translated into our language, so I didn't know its meaning, and thank you for this work.

**Comment by hoothin** [comment]
No problem, I included that meme simply because I'm a fan of the Touhou series. Can I now copy your translations into the project? - If you don't want to directly merge them, that's fine.

**Comment by vfggf95565** [comment]
No, please add it, I want to help Arabic speakers and support this great work.

**Pull request closed without merging**
